services:
  - type: web
    name: comrades-wifi
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: redirect
        source: http://colinowen.online/*
        destination: https://comradeswifi.net/:splat
        permanent: true
      - type: redirect
        source: https://colinowen.online/*
        destination: https://comradeswifi.net/:splat
        permanent: true
      - type: redirect
        source: http://www.colinowen.online/*
        destination: https://comradeswifi.net/:splat
        permanent: true
      - type: redirect
        source: https://www.colinowen.online/*
        destination: https://comradeswifi.net/:splat
        permanent: true
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
